#ifndef ASM_H
#define ASM_H

#define TMP_BUFFER_SIZE 100
#define BYTEOP 0
#define VAROP 1
#define KONSTANTOP 2

enum TOKENS {
  HALT,
  PRINTLF,
  PRINT_CHAR,
  PRINT_INT,
  PRINT_FLOAT,
  PRINT_DOUBLE,
  PUSH_CHAR,
  PUSH_INTEGER,
  PUSH_FLOAT,
  PUSH_DOUBLE,
  PUSH_STRING,
  PUSH_ARRAY_CHAR,
  PUSH_ARRAY_INT,
  PUSH_ARRAY_FLOAT,
  PUSH_ARRAY_DOUBLE,
  PUSH_ARRAY_STRING,
  PUSH_CONSTANT_CHAR,
  PUSH_CONSTANT_INT,
  PUSH_CONSTANT_FLOAT,
  PUSH_CONSTANT_DOUBLE,
  PUSH_CONSTANT_STRING,
  POP_CHAR,
  POP_INT,
  POP_FLOAT,
  POP_DOUBLE,
  POP_STRING,
  POP_TO_LOOP_INDEX,
  POP_ARRAY_CHAR,
  POP_ARRAY_INT,
  POP_ARRAY_FLOAT,
  POP_ARRAY_DOUBLE,
  POP_ARRAY_STRING,
  READ_CHAR,
  READ_INT,
  READ_FLOAT,
  READ_DOUBLE,
  READ_STRING,
  READ_ARRAY_CHAR,
  READ_ARRAY_INT,
  READ_ARRAY_FLOAT,
  READ_ARRAY_DOUBLE,
  READ_ARRAY_STRING,
  JUMP,
  JUMP_EQUAL,
  JUMP_NOT_EQUAL,
  JUMP_GREATER,
  JUMP_GREATER_EQUAL,
  JUMP_LOWER,
  JUMP_LOWER_EQUAL,
  STORE_REGISTER,
  STORE_CONSTANT_REGISTER,
  INCREMENT,
  DECREMENT,
  ADD,
  SUBSTRACT,
  MULTIPLY,
  DIVIDE,
  MODULO,
  COMPARE,
  COMMENT,
  ENDLINE,
  NAME,
  SYMBOL
};

extern char* str_tokens[];
extern int tokens_size;

void getChar();
int isVarDef(char c);
int isArrayDef(char c);
int isOp();
int isOneByteOp();
void next();
void init();
void scan();
void matchString();
void expected(char* s);
int isDefinition(char c);
enum TOKENS token;
char look;
char value[TMP_BUFFER_SIZE];
char tmp[TMP_BUFFER_SIZE];
char outBuffer [1000];
#endif
